name: on issues
on:
  issues:
    types: [opened, closed]

jobs:

  create_issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Telegram Message on Issue Creation
        uses: appleboy/telegram-action@master
        if: github.event_name == 'issues' && github.event.action == 'opened'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }} created an issue*

            *Title*: `${{ github.event.issue.title }}`

            *Status*: ${{ github.event.issue.state }}

            *Assignees*: ${{ join(github.event.issue.assignees.*.login, ', ') }}
            
            *Labels*: ${{ join(github.event.issue.labels.*.name, ', ') }}
            
            *Repository*:
            `${{ github.repository }}`
            
            [View Issue](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})

  close_issue:
    name: Close Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Telegram Message on Issue Close
        uses: appleboy/telegram-action@master
        if: github.event_name == 'issues' && github.event.action == 'closed'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }} closed an issue*

            *Title*: `${{ github.event.issue.title }}`

            *Status*: ${{ github.event.issue.state }}

            *Assignees*: ${{ join(github.event.issue.assignees.*.login, ', ') }}
            
            *Labels*: ${{ join(github.event.issue.labels.*.name, ', ') }}
            
            *Repository*:
            `${{ github.repository }}`
            
            [View Issue](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})

